package: formslider
version: '0.1.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/formslider
requires:
    redaxo: '^5.15.1'
    php:
        version: '>=8.1, <9'
    packages:                  # Plugins und Addons
        yform: "^4"
        pdfout: "^8.3"

page:
    title: translate:formslider_block_title    # Übersetzung definieren in lang/de_de.lang
    prio: 100                       # Reihenfolge in Relation zur Prio anderer Menüeinträge
    block: formslider
    icon: rex-icon fa-wpforms
    perm: formslider[]               # Berechtigung, die einer Rolle zugewiesen werden kann. z.B. `admin` für Admin, oder `formslider['xyz']` für dein eigenes Addon
    subpages:                   # Automatisches Untermenü unterhalb des Reisters von `formsliderpage` erzeugen
        table:
            title: translate:formslider_table
            icon: rex-icon fa-list
            perm: formslider[]
        docs:
            title: translate:formslider_docs
            icon: rex-icon fa-info-circle
            itemclass: pull-right
            perm: formslider[docs]
        settings:
            title: translate:formslider_settings
            icon: rex-icon fa-gears
            itemclass: pull-right
            perm: admin


installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
- src
- node_modules
- .browserslistrc
- .env
- .env.local
- .eslintrc.cjs
- .prettierrc.cjs
- .jsconfig.json
- main.js
- package.json
- postcss.config.js
- stylelint.config.js
- tailwind.config.js
- vite.config.js
- yarn.lock